# Generated by Django 4.1.4 on 2023-02-25 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to='movie/images')),
                ('duracion', models.CharField(max_length=7)),
                ('rate', models.CharField(max_length=4)),
                ('url', models.URLField(blank=True)),
                ('trailer', models.URLField(blank=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('genero', models.ManyToManyField(to='movie.genero')),
            ],
        ),
    ]
