# Generated by Django 4.1.4 on 2023-02-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='rate',
            field=models.CharField(max_length=6),
        ),
    ]
