# Generated by Django 4.1.4 on 2023-03-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_estreno'),
    ]

    operations = [
        migrations.AddField(
            model_name='estreno',
            name='imagen',
            field=models.ImageField(default=1, upload_to='estreno/images'),
            preserve_default=False,
        ),
    ]
