# Generated by Django 4.0 on 2023-09-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_pelicula_genero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['-id'], 'verbose_name': 'Pelicula', 'verbose_name_plural': 'Peliculas'},
        ),
    ]
