# Generated by Django 4.0 on 2023-09-08 16:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_pelicula_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
